export const plcCommunities: string[] = [
  "Aspen Ridge Senior Living",
  "Brentwood at Elkhart AL",
  "Brentwood at Elkhart IL",
  "Brentwood at Hobart Senior Living",
  "Brentwood at LaPorte Senior Living",
  "Brentwood at Niles Senior Living",
  "Bridges of Warwick",
  "Celebration of Jensen Beach",
  "Celebration Villa of Altoona",
  "Celebration Villa of Berwick",
  "Celebration Villa of Chippewa",
  "Celebration Villa of Deer Creek",
  "Celebration Villa of Dillsburg",
  "Celebration Villa of Exeter",
  "Celebration Villa of Hearthstone East",
  "Celebration Villa of Hearthstone West",
  "Celebration Villa of Highland Crossing",
  "Celebration Villa of Lakemont Farms",
  "Celebration Villa of Lebanon",
  "Celebration Villa of Lewisburg",
  "Celebration Villa of Loyalsock",
  "Celebration Villa of Manresa",
  "Celebration Villa of Martinsburg",
  "Celebration Villa of Mid Valley",
  "Celebration Villa of Newburgh",
  "Celebration Villa of Nittany Valley",
  "Celebration Villa of Reedsville",
  "Celebration Villa of Richmond",
  "Celebration Villa of Shippensburg",
  "Celebration Villa of South Hills",
  "Celebration Villa of Summit Hills",
  "Celebration Villa of Tavaras",
  "Celebration Villa of Teays Valley",
  "Celebration Villa of West Palm Beach",
  "Celebration Villa of Winter Haven",
  "Celebration Villa of York",
  "Dresher Estates",
  "Eagleview Landing",
  "Independence Court of Hyattsville",
  "Johnson Care Suites (OKC)",
  "Lake Meadows Senior Living",
  "New Standard of Millville",
  "New Standard-Egg Harbor",
  "New Standard-Hammonton",
  "Poet's Walk Leesburg",
  "Poet's Walk Warrenton",
  "Sky Active Cherry Laurel",
  "Sky Active Desoto Beach Club",
  "Sky Active Las Palmas",
  "Sky Active Marion Woods",
  "Sky Active Regency Residents",
  "Sky Active Sterling Court",
  "Sky Active University Pines",
  "Sky Active Venetian Gardens",
  "Tanglewood Trace Senior Living",
  "Tawas Village Senior Living",
  "The Courtland of Holland Meadows",
  "The Courtland of Northview",
  "The Courtland of Riverside Gardens",
  "The Courtland of Wyoming",
  "The Crossing of Riverview",
];
